version: '3.8'

services:
  symfony_app:
    build: .
    ports:
      - "85:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
